{% set name = "hxnfly" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d0481a4d9db974b43459688d52ae2d595923308af45a3b1383ef3841c72fdc70

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - hxntools
    - ppmac
    - xray-vision

test:
  imports:
    - hxnfly

about:
  home: https://github.com/NSLS-II-HXN/hxnfly
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Tools for NSLS-II HXN fly scans

extra:
  recipe-maintainers:
    - mrakitin
    - dmgav
    - kbeeperez
    - conda-forge/event-model
