{% set name = "hxnfly" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7193655ad285949875aba8ef7e307100765561d1d4c0070a37c0d38a1c3c2d72

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - hxntools
    - ppmac
    - xray-vision

test:
  requires:
    - python {{ python_min }}
  imports:
    - hxnfly

about:
  home: https://github.com/NSLS-II-HXN/hxnfly
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Tools for NSLS-II HXN fly scans

extra:
  recipe-maintainers:
    - mrakitin
    - dmgav
    - kbeeperez
    - conda-forge/event-model
